apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-tech-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz-tech
  template:
    metadata:
      labels:
        app: xyz-tech
    spec:
      containers:
      - name: xyz-tech-container
        image: tonytmv/xyz_tech:IMAGE_TAG
        ports:
        - containerPort: 8080
