apiVersion: v1
kind: Service
metadata:
  name: xyz-tech-service
spec:
  type: NodePort       # Change this from ClusterIP to NodePort
  selector:
    app: xyz-tech
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080   # Optional, Kubernetes will assign if omitted
